### ISSUE TITLE
Make 2 builds: One with opengl and vulkan

### ISSUE THREAD

**Issue by MolotovCherry** [deevus/zed-windows-builds#1]
The blade backend doesn't always support vulkan on users systems.

The build could enable opengl for one and vulkan for another so people can use either

This seems fairly simple. Just set `RUSTFLAGS="--cfg gles"` or `RUSTFLAGS="--cfg vulkan"` for the build (vulkan should be the default, so it doesn't need to be explicitly enabled)

More info: https://crates.io/crates/blade-graphics

(The below issue is now resolved, but this issue can probably remain open for some time, since opengl support seems to not quite be ready yet)

~~Edit: This issue may have to wait a bit, as it appears the dep has a compilation bug in opengl mode. (Probably will have to file this with Zed; edit: https://github.com/zed-industries/zed/issues/16677)~~

~~Edit 2: Opened PR to fix this: https://github.com/zed-industries/zed/pull/16682~~

**Comment by messense** [comment]
+1, I'm getting `[ERROR] Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } })` currently using the current vulkan build.

**Comment by deevus** [comment]
If you wanted to ship an OpenGL build, I would accept a PR to add one.

**Comment by 2dragonly** [comment]
The latest build doesn't work on older laptops without a GPU. Please add support for OpenGL to ensure compatibility with older hardware.
