### ISSUE TITLE
it crachs when I start it

### ISSUE THREAD

**Issue by MElkmeshi** [deevus/zed-windows-builds#17]
![image](https://github.com/user-attachments/assets/adaff1a3-a057-4dba-861f-d60c85aa8496)

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Ram: 16.0 GB (15.8 GB usable)
GPU: Nvidia MX450

**Comment by deevus** [comment]
As per the README: This isn't a support channel.
