### ISSUE TITLE
Include Zed Windows Builds in the winget

### ISSUE THREAD

**Issue by joaovjo** [deevus/zed-windows-builds#18]
en-US:

> Including Zed builds for Windows in winget would be an even better way of distributing updates, since winget is native to Windows and therefore doesn't need a third-party tool such as scoop or chocolatey.

pt-BR:

> Incluir as builds do Zed para Windows no winget seria uma forma ainda melhor de distribuir as atualizações, já que o winget é nativo do Windows e portanto não necessita da ferramenta de terceiros, como o scoop ou chocolatey.

PS: Translated with DeepL

**Comment by deevus** [comment]
Since this is not an official build of Zed, I'm not sure submitting it to winget is the right call at this time. I would be worried that winget would make it so trivial to get Zed for Windows, that it will just create tension and support issues for the core Zed team.
