### ISSUE TITLE
the app not launch

### ISSUE THREAD

**Issue by Louis-htmlcss** [deevus/zed-windows-builds#4]
the app not launch

**Comment by dealenx** [comment]
I have the same problem

**Comment by wuchunpeng777** [comment]
same problem

**Comment by red-co** [comment]
launch on windows 11, not support on windows 10, I don't know why

**Comment by red-co** [comment]
Jump to amd/intel/Nvidia graphics driver download page, choice latest version, download,
Now, Zed work,
Because of "vk_khr_dynamic_rendering  support"

**Comment by Louis-htmlcss** [comment]
> launch on windows 11, not support on windows 10, I don't know why

I am on windows 11

**Comment by Louis-htmlcss** [comment]
> Jump to amd/intel/Nvidia graphics driver download page, choice latest version, download, Now, Zed work, Because of "vk_khr_dynamic_rendering support"

thanks its working

**Comment by wuchunpeng777** [comment]
is it possible run on win10?
