### ISSUE TITLE
Why  I  can't  start zed after installing  

### ISSUE THREAD

**Issue by Super1Windcloud** [deevus/zed-windows-builds#6]

**Comment by waldnercharles** [comment]
This was just fixed 6 hours ago it looks like. Try again tomorrow, or build manually. https://github.com/zed-industries/zed/issues/18610#event-14589373983

**Comment by Super1Windcloud** [comment]
OK,  but  I   select  vscode  or  cursor   at now

**Comment by deevus** [comment]
Lol good for you
